### PR TITLE
remove/sharing

### PR DESCRIPTION
**Pull request by decanus**
I do not understand the rationale to keeping a list of `peers` and a list of those we share with. In my opinion if we have a peer we should share with them by default, otherwise there is no reason to keep said peer in a list of our peers.

### CODE REVIEW

**Comment by oskarth** [comment]
By default we might, but who you are connected to as a peer isn't necessarily same as who you share with. Especially in other network topologies. They are different concepts IMO.

**Comment by decanus** [comment]
@oskarth is this relevant to the minimal version? If yes I might consider solving this in a different manner by moving it out into a seperate interface where applications can select how they share etc.

**Comment by oskarth** [comment]
You might be right. I guess the actual 'peer' here is actually dealt with at the Whisper level, so I suppose we can de-emphasize this and focus on 'sharing' concept?

**Comment by oskarth** [comment]
Part of clarifying vocabulary, peer to me is more about direct network connections

**Pull request merged**
