### PR TITLE
enhancement/share-messages

### PR DESCRIPTION
**Pull request by decanus**
This feature shares any messages we receive with all our peers.

### CODE REVIEW

**Comment by oskarth** [comment]
> This feature shares any messages we receive with all our peers.

Hm, what does this mean more precisely? It isn't scoped by sync id? Does this mean I can just send you a random message and you'll propagate it?

**Comment by decanus** [comment]
@oskarth its scoped by group, if I recieve a message in group `x` I will share it with any of my peers in group x

**Comment by oskarth** [comment]
Ok sg

**Review by oskarth — APPROVED** [review]

**Comment by decanus** [comment]
@oskarth are we happy with this actually being merged or do we need any further discussion?

**Pull request merged**
